### ISSUE TITLE
Auto Rename bug

### ISSUE THREAD

**Issue by MattsBos** [ClanBadJas/ClanBotJas#26]
When joining a scaling voice auto rename works fine.
When moving between voice channels, auto rename works fine.
When changing status without moving/joining a channel, auto rename does not update.
When changing status from playing to none does not rename voice to default and does not update.
When user that dropped status disconnects while other user is in the same channel, auto rename does not update.

**Comment by rutgerbeltman** [comment]
pycord changed the api:
https://docs.pycord.dev/en/stable/search.html?q=on_member_update&check_keywords=yes&area=default

**Comment by rutgerbeltman** [comment]
#22 has the fix
